services:
  os-backend:
    image: os-backend
    build:
      context: ./Backend/Online-Store-Backend
      dockerfile: ./Online-Store-Backend/Dockerfile
    volumes:
      - ./Backend/Online-Store-Backend/Online-Store-Backend/wwwroot/:/app/wwwroot:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - 5000:8080
    privileged: true
    depends_on: 
      - db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: OnlineStoreDB
    ports:
    - 5432:5432