services:
  todoapi:
    image: todoapi
    build:
      context: ./Backend/Online-Store-Backend
      dockerfile: ./Online-Store-Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:8080
    depends_on: 
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: OnlineStoreDB
    ports:
    - 5432:5432
      