--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-07-30 10:37:50

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 83188)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 83194)
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    "ID" bigint NOT NULL,
    "Name" text,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 218 (class 1259 OID 83193)
-- Name: category_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."category_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 83226)
-- Name: category_prop; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category_prop (
    "ID" bigint NOT NULL,
    "CategoryID" bigint NOT NULL,
    "PropName" character varying(100) NOT NULL,
    "ValueType" integer NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 226 (class 1259 OID 83225)
-- Name: category_prop_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category_prop ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."category_prop_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 83202)
-- Name: employee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee (
    "ID" bigint NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "PhoneNum" character varying(20) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Gender" boolean,
    "BirthDate" timestamp with time zone,
    "Login" character varying(255) NOT NULL,
    "PasswordHash" character varying(255),
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 220 (class 1259 OID 83201)
-- Name: employee_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."employee_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 83263)
-- Name: employee_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_permission (
    "ID" bigint NOT NULL,
    "EmployeeID" bigint NOT NULL,
    "PermissionID" bigint NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UpdateDateTime" timestamp with time zone NOT NULL
);


--
-- TOC entry 232 (class 1259 OID 83262)
-- Name: employee_permission_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee_permission ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."employee_permission_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 83250)
-- Name: employee_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_token (
    "ID" bigint NOT NULL,
    "EmployeeID" bigint NOT NULL,
    "ExpirationDate" timestamp with time zone NOT NULL,
    "Token" text,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UpdateDateTime" timestamp with time zone NOT NULL
);


--
-- TOC entry 230 (class 1259 OID 83249)
-- Name: employee_token_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee_token ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."employee_token_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 83279)
-- Name: order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."order" (
    "ID" bigint NOT NULL,
    "TotalPrice" double precision NOT NULL,
    "UserID" bigint NOT NULL,
    "Status" integer NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 234 (class 1259 OID 83278)
-- Name: order_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."order" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."order_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 83332)
-- Name: order_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_product (
    "ID" bigint NOT NULL,
    "OrderID" bigint NOT NULL,
    "ProductID" bigint NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UpdateDateTime" timestamp with time zone NOT NULL
);


--
-- TOC entry 242 (class 1259 OID 83331)
-- Name: order_product_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_product ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."order_product_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 83210)
-- Name: permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permission (
    "ID" bigint NOT NULL,
    "Name" text,
    "Description" text,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 83209)
-- Name: permission_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permission ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."permission_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 83237)
-- Name: product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product (
    "ID" bigint NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Description" text,
    "CategoryID" bigint,
    "Price" double precision NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 228 (class 1259 OID 83236)
-- Name: product_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."product_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 83303)
-- Name: product_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_image (
    "ID" bigint NOT NULL,
    "ImageAddress" text,
    "ProductID" bigint NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 238 (class 1259 OID 83302)
-- Name: product_image_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_image ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."product_image_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 83316)
-- Name: product_property_value; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_property_value (
    "ID" bigint NOT NULL,
    "ProductID" bigint NOT NULL,
    "PropID" bigint NOT NULL,
    "Value" character varying(100),
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UpdateDateTime" timestamp with time zone NOT NULL
);


--
-- TOC entry 240 (class 1259 OID 83315)
-- Name: product_property_value_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_property_value ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."product_property_value_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 83218)
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    "ID" bigint NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "PhoneNum" character varying(20) NOT NULL,
    "Email" character varying(100),
    "Gender" boolean,
    "BirthDate" timestamp with time zone,
    "Login" character varying(255),
    "PasswordHash" character varying(255),
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 224 (class 1259 OID 83217)
-- Name: user_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."user_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 83290)
-- Name: user_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_token (
    "ID" bigint NOT NULL,
    "UserID" bigint NOT NULL,
    "ExpirationDate" timestamp with time zone NOT NULL,
    "Token" text,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UpdateDateTime" timestamp with time zone NOT NULL
);


--
-- TOC entry 236 (class 1259 OID 83289)
-- Name: user_token_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_token ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."user_token_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4807 (class 2606 OID 83192)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4809 (class 2606 OID 83200)
-- Name: category PK_category; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT "PK_category" PRIMARY KEY ("ID");


--
-- TOC entry 4818 (class 2606 OID 83230)
-- Name: category_prop PK_category_prop; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_prop
    ADD CONSTRAINT "PK_category_prop" PRIMARY KEY ("ID");


--
-- TOC entry 4811 (class 2606 OID 83208)
-- Name: employee PK_employee; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT "PK_employee" PRIMARY KEY ("ID");


--
-- TOC entry 4828 (class 2606 OID 83267)
-- Name: employee_permission PK_employee_permission; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_permission
    ADD CONSTRAINT "PK_employee_permission" PRIMARY KEY ("ID");


--
-- TOC entry 4824 (class 2606 OID 83256)
-- Name: employee_token PK_employee_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_token
    ADD CONSTRAINT "PK_employee_token" PRIMARY KEY ("ID");


--
-- TOC entry 4831 (class 2606 OID 83283)
-- Name: order PK_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT "PK_order" PRIMARY KEY ("ID");


--
-- TOC entry 4845 (class 2606 OID 83336)
-- Name: order_product PK_order_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_product
    ADD CONSTRAINT "PK_order_product" PRIMARY KEY ("ID");


--
-- TOC entry 4813 (class 2606 OID 83216)
-- Name: permission PK_permission; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT "PK_permission" PRIMARY KEY ("ID");


--
-- TOC entry 4821 (class 2606 OID 83243)
-- Name: product PK_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT "PK_product" PRIMARY KEY ("ID");


--
-- TOC entry 4837 (class 2606 OID 83309)
-- Name: product_image PK_product_image; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT "PK_product_image" PRIMARY KEY ("ID");


--
-- TOC entry 4841 (class 2606 OID 83320)
-- Name: product_property_value PK_product_property_value; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_property_value
    ADD CONSTRAINT "PK_product_property_value" PRIMARY KEY ("ID");


--
-- TOC entry 4815 (class 2606 OID 83224)
-- Name: user PK_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT "PK_user" PRIMARY KEY ("ID");


--
-- TOC entry 4834 (class 2606 OID 83296)
-- Name: user_token PK_user_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_token
    ADD CONSTRAINT "PK_user_token" PRIMARY KEY ("ID");


--
-- TOC entry 4816 (class 1259 OID 83347)
-- Name: IX_category_prop_CategoryID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_category_prop_CategoryID" ON public.category_prop USING btree ("CategoryID");


--
-- TOC entry 4825 (class 1259 OID 83348)
-- Name: IX_employee_permission_EmployeeID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_employee_permission_EmployeeID" ON public.employee_permission USING btree ("EmployeeID");


--
-- TOC entry 4826 (class 1259 OID 83349)
-- Name: IX_employee_permission_PermissionID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_employee_permission_PermissionID" ON public.employee_permission USING btree ("PermissionID");


--
-- TOC entry 4822 (class 1259 OID 83350)
-- Name: IX_employee_token_EmployeeID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_employee_token_EmployeeID" ON public.employee_token USING btree ("EmployeeID");


--
-- TOC entry 4829 (class 1259 OID 83351)
-- Name: IX_order_UserID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_order_UserID" ON public."order" USING btree ("UserID");


--
-- TOC entry 4842 (class 1259 OID 83352)
-- Name: IX_order_product_OrderID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_order_product_OrderID" ON public.order_product USING btree ("OrderID");


--
-- TOC entry 4843 (class 1259 OID 83353)
-- Name: IX_order_product_ProductID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_order_product_ProductID" ON public.order_product USING btree ("ProductID");


--
-- TOC entry 4819 (class 1259 OID 83354)
-- Name: IX_product_CategoryID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_product_CategoryID" ON public.product USING btree ("CategoryID");


--
-- TOC entry 4835 (class 1259 OID 83355)
-- Name: IX_product_image_ProductID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_product_image_ProductID" ON public.product_image USING btree ("ProductID");


--
-- TOC entry 4838 (class 1259 OID 83356)
-- Name: IX_product_property_value_ProductID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_product_property_value_ProductID" ON public.product_property_value USING btree ("ProductID");


--
-- TOC entry 4839 (class 1259 OID 83357)
-- Name: IX_product_property_value_PropID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_product_property_value_PropID" ON public.product_property_value USING btree ("PropID");


--
-- TOC entry 4832 (class 1259 OID 83358)
-- Name: IX_user_token_UserID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_user_token_UserID" ON public.user_token USING btree ("UserID");


--
-- TOC entry 4846 (class 2606 OID 83231)
-- Name: category_prop FK_category_prop_category_CategoryID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_prop
    ADD CONSTRAINT "FK_category_prop_category_CategoryID" FOREIGN KEY ("CategoryID") REFERENCES public.category("ID") ON DELETE CASCADE;


--
-- TOC entry 4849 (class 2606 OID 83268)
-- Name: employee_permission FK_employee_permission_employee_EmployeeID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_permission
    ADD CONSTRAINT "FK_employee_permission_employee_EmployeeID" FOREIGN KEY ("EmployeeID") REFERENCES public.employee("ID") ON DELETE CASCADE;


--
-- TOC entry 4850 (class 2606 OID 83273)
-- Name: employee_permission FK_employee_permission_permission_PermissionID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_permission
    ADD CONSTRAINT "FK_employee_permission_permission_PermissionID" FOREIGN KEY ("PermissionID") REFERENCES public.permission("ID") ON DELETE CASCADE;


--
-- TOC entry 4848 (class 2606 OID 83257)
-- Name: employee_token FK_employee_token_employee_EmployeeID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_token
    ADD CONSTRAINT "FK_employee_token_employee_EmployeeID" FOREIGN KEY ("EmployeeID") REFERENCES public.employee("ID") ON DELETE CASCADE;


--
-- TOC entry 4856 (class 2606 OID 83337)
-- Name: order_product FK_order_product_order_OrderID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_product
    ADD CONSTRAINT "FK_order_product_order_OrderID" FOREIGN KEY ("OrderID") REFERENCES public."order"("ID") ON DELETE CASCADE;


--
-- TOC entry 4857 (class 2606 OID 83342)
-- Name: order_product FK_order_product_product_ProductID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_product
    ADD CONSTRAINT "FK_order_product_product_ProductID" FOREIGN KEY ("ProductID") REFERENCES public.product("ID") ON DELETE CASCADE;


--
-- TOC entry 4851 (class 2606 OID 83284)
-- Name: order FK_order_user_UserID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT "FK_order_user_UserID" FOREIGN KEY ("UserID") REFERENCES public."user"("ID") ON DELETE CASCADE;


--
-- TOC entry 4847 (class 2606 OID 83244)
-- Name: product FK_product_category_CategoryID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT "FK_product_category_CategoryID" FOREIGN KEY ("CategoryID") REFERENCES public.category("ID");


--
-- TOC entry 4853 (class 2606 OID 83310)
-- Name: product_image FK_product_image_product_ProductID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT "FK_product_image_product_ProductID" FOREIGN KEY ("ProductID") REFERENCES public.product("ID") ON DELETE CASCADE;


--
-- TOC entry 4854 (class 2606 OID 83321)
-- Name: product_property_value FK_product_property_value_category_prop_PropID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_property_value
    ADD CONSTRAINT "FK_product_property_value_category_prop_PropID" FOREIGN KEY ("PropID") REFERENCES public.category_prop("ID") ON DELETE CASCADE;


--
-- TOC entry 4855 (class 2606 OID 83326)
-- Name: product_property_value FK_product_property_value_product_ProductID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_property_value
    ADD CONSTRAINT "FK_product_property_value_product_ProductID" FOREIGN KEY ("ProductID") REFERENCES public.product("ID") ON DELETE CASCADE;


--
-- TOC entry 4852 (class 2606 OID 83297)
-- Name: user_token FK_user_token_user_UserID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_token
    ADD CONSTRAINT "FK_user_token_user_UserID" FOREIGN KEY ("UserID") REFERENCES public."user"("ID") ON DELETE CASCADE;


-- Completed on 2025-07-30 10:37:50

--
-- PostgreSQL database dump complete
--

