--
-- PostgreSQL database dump
--

\restrict nYRd9dF5zsmCtehn2tnGBp9a7ndW78umYB5aJUBSLDDAXDL2XzeoqbJagLDZjgk

-- Dumped from database version 17.6 (Debian 17.6-1.pgdg13+1)
-- Dumped by pg_dump version 17.6

-- Started on 2025-09-21 09:05:55 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 16395)
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    "ID" bigint NOT NULL,
    "Name" text,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 218 (class 1259 OID 16394)
-- Name: category_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."category_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16427)
-- Name: category_prop; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category_prop (
    "ID" bigint NOT NULL,
    "CategoryID" bigint NOT NULL,
    "PropName" character varying(100) NOT NULL,
    "ValueType" integer NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 226 (class 1259 OID 16426)
-- Name: category_prop_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category_prop ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."category_prop_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16403)
-- Name: employee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee (
    "ID" bigint NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "PhoneNum" character varying(20) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Gender" boolean,
    "BirthDate" timestamp with time zone,
    "Login" character varying(255) NOT NULL,
    "PasswordHash" character varying(255),
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 220 (class 1259 OID 16402)
-- Name: employee_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."employee_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16464)
-- Name: employee_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_permission (
    "ID" bigint NOT NULL,
    "EmployeeID" bigint NOT NULL,
    "PermissionID" bigint NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UpdateDateTime" timestamp with time zone NOT NULL
);


--
-- TOC entry 232 (class 1259 OID 16463)
-- Name: employee_permission_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee_permission ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."employee_permission_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16451)
-- Name: employee_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_token (
    "ID" bigint NOT NULL,
    "EmployeeID" bigint NOT NULL,
    "ExpirationDate" timestamp with time zone NOT NULL,
    "Token" text,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UpdateDateTime" timestamp with time zone NOT NULL
);


--
-- TOC entry 230 (class 1259 OID 16450)
-- Name: employee_token_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee_token ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."employee_token_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16480)
-- Name: order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."order" (
    "ID" bigint NOT NULL,
    "UserID" bigint NOT NULL,
    "Status" integer NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 234 (class 1259 OID 16479)
-- Name: order_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."order" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."order_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16533)
-- Name: order_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_product (
    "ID" bigint NOT NULL,
    "OrderID" bigint NOT NULL,
    "ProductID" bigint NOT NULL,
    "PriceWhenAdded" double precision NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UpdateDateTime" timestamp with time zone NOT NULL
);


--
-- TOC entry 242 (class 1259 OID 16532)
-- Name: order_product_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_product ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."order_product_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16411)
-- Name: permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permission (
    "ID" bigint NOT NULL,
    "Name" text,
    "Description" text,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 16410)
-- Name: permission_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permission ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."permission_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16438)
-- Name: product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product (
    "ID" bigint NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Description" text,
    "CategoryID" bigint,
    "Price" double precision NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 228 (class 1259 OID 16437)
-- Name: product_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."product_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16504)
-- Name: product_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_image (
    "ID" bigint NOT NULL,
    "ImageAddress" text,
    "ProductID" bigint NOT NULL,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 238 (class 1259 OID 16503)
-- Name: product_image_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_image ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."product_image_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16517)
-- Name: product_property_value; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_property_value (
    "ID" bigint NOT NULL,
    "ProductID" bigint NOT NULL,
    "PropID" bigint NOT NULL,
    "Value" character varying(100),
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UpdateDateTime" timestamp with time zone NOT NULL
);


--
-- TOC entry 240 (class 1259 OID 16516)
-- Name: product_property_value_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_property_value ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."product_property_value_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16419)
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    "ID" bigint NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "PhoneNum" character varying(20) NOT NULL,
    "Email" character varying(100),
    "Gender" boolean,
    "BirthDate" timestamp with time zone,
    "Login" character varying(255),
    "PasswordHash" character varying(255),
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 224 (class 1259 OID 16418)
-- Name: user_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."user_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16491)
-- Name: user_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_token (
    "ID" bigint NOT NULL,
    "UserID" bigint NOT NULL,
    "ExpirationDate" timestamp with time zone NOT NULL,
    "Token" text,
    "CreatedDateTime" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UpdateDateTime" timestamp with time zone NOT NULL
);


--
-- TOC entry 236 (class 1259 OID 16490)
-- Name: user_token_ID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_token ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."user_token_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3339 (class 2606 OID 16393)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3341 (class 2606 OID 16401)
-- Name: category PK_category; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT "PK_category" PRIMARY KEY ("ID");


--
-- TOC entry 3356 (class 2606 OID 16431)
-- Name: category_prop PK_category_prop; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_prop
    ADD CONSTRAINT "PK_category_prop" PRIMARY KEY ("ID");


--
-- TOC entry 3346 (class 2606 OID 16409)
-- Name: employee PK_employee; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT "PK_employee" PRIMARY KEY ("ID");


--
-- TOC entry 3366 (class 2606 OID 16468)
-- Name: employee_permission PK_employee_permission; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_permission
    ADD CONSTRAINT "PK_employee_permission" PRIMARY KEY ("ID");


--
-- TOC entry 3362 (class 2606 OID 16457)
-- Name: employee_token PK_employee_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_token
    ADD CONSTRAINT "PK_employee_token" PRIMARY KEY ("ID");


--
-- TOC entry 3369 (class 2606 OID 16484)
-- Name: order PK_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT "PK_order" PRIMARY KEY ("ID");


--
-- TOC entry 3383 (class 2606 OID 16537)
-- Name: order_product PK_order_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_product
    ADD CONSTRAINT "PK_order_product" PRIMARY KEY ("ID");


--
-- TOC entry 3348 (class 2606 OID 16417)
-- Name: permission PK_permission; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT "PK_permission" PRIMARY KEY ("ID");


--
-- TOC entry 3359 (class 2606 OID 16444)
-- Name: product PK_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT "PK_product" PRIMARY KEY ("ID");


--
-- TOC entry 3375 (class 2606 OID 16510)
-- Name: product_image PK_product_image; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT "PK_product_image" PRIMARY KEY ("ID");


--
-- TOC entry 3379 (class 2606 OID 16521)
-- Name: product_property_value PK_product_property_value; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_property_value
    ADD CONSTRAINT "PK_product_property_value" PRIMARY KEY ("ID");


--
-- TOC entry 3353 (class 2606 OID 16425)
-- Name: user PK_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT "PK_user" PRIMARY KEY ("ID");


--
-- TOC entry 3372 (class 2606 OID 16497)
-- Name: user_token PK_user_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_token
    ADD CONSTRAINT "PK_user_token" PRIMARY KEY ("ID");


--
-- TOC entry 3354 (class 1259 OID 16548)
-- Name: IX_category_prop_CategoryID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_category_prop_CategoryID" ON public.category_prop USING btree ("CategoryID");


--
-- TOC entry 3342 (class 1259 OID 16549)
-- Name: IX_employee_Email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_employee_Email" ON public.employee USING btree ("Email");


--
-- TOC entry 3343 (class 1259 OID 16550)
-- Name: IX_employee_Login; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_employee_Login" ON public.employee USING btree ("Login");


--
-- TOC entry 3344 (class 1259 OID 16551)
-- Name: IX_employee_PhoneNum; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_employee_PhoneNum" ON public.employee USING btree ("PhoneNum");


--
-- TOC entry 3363 (class 1259 OID 16552)
-- Name: IX_employee_permission_EmployeeID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_employee_permission_EmployeeID" ON public.employee_permission USING btree ("EmployeeID");


--
-- TOC entry 3364 (class 1259 OID 16553)
-- Name: IX_employee_permission_PermissionID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_employee_permission_PermissionID" ON public.employee_permission USING btree ("PermissionID");


--
-- TOC entry 3360 (class 1259 OID 16554)
-- Name: IX_employee_token_EmployeeID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_employee_token_EmployeeID" ON public.employee_token USING btree ("EmployeeID");


--
-- TOC entry 3367 (class 1259 OID 16555)
-- Name: IX_order_UserID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_order_UserID" ON public."order" USING btree ("UserID");


--
-- TOC entry 3380 (class 1259 OID 16556)
-- Name: IX_order_product_OrderID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_order_product_OrderID" ON public.order_product USING btree ("OrderID");


--
-- TOC entry 3381 (class 1259 OID 16557)
-- Name: IX_order_product_ProductID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_order_product_ProductID" ON public.order_product USING btree ("ProductID");


--
-- TOC entry 3357 (class 1259 OID 16558)
-- Name: IX_product_CategoryID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_product_CategoryID" ON public.product USING btree ("CategoryID");


--
-- TOC entry 3373 (class 1259 OID 16559)
-- Name: IX_product_image_ProductID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_product_image_ProductID" ON public.product_image USING btree ("ProductID");


--
-- TOC entry 3376 (class 1259 OID 16560)
-- Name: IX_product_property_value_ProductID_PropID; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_product_property_value_ProductID_PropID" ON public.product_property_value USING btree ("ProductID", "PropID");


--
-- TOC entry 3377 (class 1259 OID 16561)
-- Name: IX_product_property_value_PropID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_product_property_value_PropID" ON public.product_property_value USING btree ("PropID");


--
-- TOC entry 3349 (class 1259 OID 16562)
-- Name: IX_user_Email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_user_Email" ON public."user" USING btree ("Email");


--
-- TOC entry 3350 (class 1259 OID 16563)
-- Name: IX_user_Login; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_user_Login" ON public."user" USING btree ("Login");


--
-- TOC entry 3351 (class 1259 OID 16564)
-- Name: IX_user_PhoneNum; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_user_PhoneNum" ON public."user" USING btree ("PhoneNum");


--
-- TOC entry 3370 (class 1259 OID 16565)
-- Name: IX_user_token_UserID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_user_token_UserID" ON public.user_token USING btree ("UserID");


--
-- TOC entry 3384 (class 2606 OID 16432)
-- Name: category_prop FK_category_prop_category_CategoryID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_prop
    ADD CONSTRAINT "FK_category_prop_category_CategoryID" FOREIGN KEY ("CategoryID") REFERENCES public.category("ID") ON DELETE CASCADE;


--
-- TOC entry 3387 (class 2606 OID 16469)
-- Name: employee_permission FK_employee_permission_employee_EmployeeID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_permission
    ADD CONSTRAINT "FK_employee_permission_employee_EmployeeID" FOREIGN KEY ("EmployeeID") REFERENCES public.employee("ID") ON DELETE CASCADE;


--
-- TOC entry 3388 (class 2606 OID 16474)
-- Name: employee_permission FK_employee_permission_permission_PermissionID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_permission
    ADD CONSTRAINT "FK_employee_permission_permission_PermissionID" FOREIGN KEY ("PermissionID") REFERENCES public.permission("ID") ON DELETE CASCADE;


--
-- TOC entry 3386 (class 2606 OID 16458)
-- Name: employee_token FK_employee_token_employee_EmployeeID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_token
    ADD CONSTRAINT "FK_employee_token_employee_EmployeeID" FOREIGN KEY ("EmployeeID") REFERENCES public.employee("ID") ON DELETE CASCADE;


--
-- TOC entry 3394 (class 2606 OID 16538)
-- Name: order_product FK_order_product_order_OrderID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_product
    ADD CONSTRAINT "FK_order_product_order_OrderID" FOREIGN KEY ("OrderID") REFERENCES public."order"("ID") ON DELETE CASCADE;


--
-- TOC entry 3395 (class 2606 OID 16543)
-- Name: order_product FK_order_product_product_ProductID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_product
    ADD CONSTRAINT "FK_order_product_product_ProductID" FOREIGN KEY ("ProductID") REFERENCES public.product("ID") ON DELETE CASCADE;


--
-- TOC entry 3389 (class 2606 OID 16485)
-- Name: order FK_order_user_UserID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT "FK_order_user_UserID" FOREIGN KEY ("UserID") REFERENCES public."user"("ID") ON DELETE CASCADE;


--
-- TOC entry 3385 (class 2606 OID 16445)
-- Name: product FK_product_category_CategoryID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT "FK_product_category_CategoryID" FOREIGN KEY ("CategoryID") REFERENCES public.category("ID");


--
-- TOC entry 3391 (class 2606 OID 16511)
-- Name: product_image FK_product_image_product_ProductID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT "FK_product_image_product_ProductID" FOREIGN KEY ("ProductID") REFERENCES public.product("ID") ON DELETE CASCADE;


--
-- TOC entry 3392 (class 2606 OID 16522)
-- Name: product_property_value FK_product_property_value_category_prop_PropID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_property_value
    ADD CONSTRAINT "FK_product_property_value_category_prop_PropID" FOREIGN KEY ("PropID") REFERENCES public.category_prop("ID") ON DELETE CASCADE;


--
-- TOC entry 3393 (class 2606 OID 16527)
-- Name: product_property_value FK_product_property_value_product_ProductID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_property_value
    ADD CONSTRAINT "FK_product_property_value_product_ProductID" FOREIGN KEY ("ProductID") REFERENCES public.product("ID") ON DELETE CASCADE;


--
-- TOC entry 3390 (class 2606 OID 16498)
-- Name: user_token FK_user_token_user_UserID; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_token
    ADD CONSTRAINT "FK_user_token_user_UserID" FOREIGN KEY ("UserID") REFERENCES public."user"("ID") ON DELETE CASCADE;


-- Completed on 2025-09-21 09:05:55 UTC

--
-- PostgreSQL database dump complete
--

\unrestrict nYRd9dF5zsmCtehn2tnGBp9a7ndW78umYB5aJUBSLDDAXDL2XzeoqbJagLDZjgk

